all:
  hosts:
    dasbox:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: /usr/bin/python2
    ubuntu2:
      ansible_host: ec2-54-196-158-62.compute-1.amazonaws.com
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ec2-user/Linux_Box_2.pem
      ansible_python_interpreter: /usr/bin/python3
      